Repository tombi-toml/tombi, pull requests merged in 2025-05, with the labels that each got.

#290 feat: add TOML language support for Zed editor
  Cargo.lock
  Cargo.toml
  editors/zed/.gitignore
  editors/zed/Cargo.toml
  editors/zed/extension.toml
  editors/zed/languages/toml/brackets.scm
  editors/zed/languages/toml/config.toml
  editors/zed/languages/toml/highlights.scm
  editors/zed/languages/toml/indents.scm
  editors/zed/languages/toml/outline.scm
  editors/zed/languages/toml/overrides.scm
  editors/zed/languages/toml/redactions.scm
  editors/zed/languages/toml/textobjects.scm
  editors/zed/src/lib.rs
  rust/serde_tombi/src/de.rs
  sample.toml
  tombi.toml
Labels: enhancement

#292 feat: support tomlValidation in package.json
  Cargo.lock
  crates/tombi-schema-store/src/store.rs
  crates/tombi-server/Cargo.toml
  crates/tombi-server/src/backend.rs
  crates/tombi-server/src/handler.rs
  crates/tombi-server/src/handler/associate_schema.rs
  crates/tombi-server/src/lib.rs
  editors/vscode/package.json
  editors/vscode/src/extention/index.ts
  editors/vscode/src/lsp/client.ts
  editors/vscode/src/tomlValidation.ts
  pnpm-lock.yaml
Labels: enhancement

#295 Update menubar
  docs/src/components/Sidebar.tsx
  docs/src/components/header/HeaderDropdown.tsx
  docs/src/components/header/HeaderDropdownItem.tsx
  docs/src/components/header/HeaderLogo.tsx
  docs/src/components/header/HeaderSearch.tsx
Labels: documentation

#303 doc: update header
  docs/src/components/header/HeaderDropdown.tsx
  docs/src/components/header/HeaderSearch.tsx
  docs/src/components/header/HeaderTabs.tsx
  docs/src/components/header/index.tsx
  docs/tsconfig.json
Labels: documentation

#304 chore: update Cargo.toml dependencies to use workspace syntax
  crates/tombi-ast-editor/Cargo.toml
  crates/tombi-ast/Cargo.toml
  crates/tombi-config/Cargo.toml
  crates/tombi-date-time/Cargo.toml
  crates/tombi-diagnostic/Cargo.toml
  crates/tombi-document-tree/Cargo.toml
  crates/tombi-document/Cargo.toml
  crates/tombi-extension/Cargo.toml
  crates/tombi-formatter/Cargo.toml
  crates/tombi-json-lexer/Cargo.toml
  crates/tombi-json-syntax/Cargo.toml
  crates/tombi-json-value/Cargo.toml
  crates/tombi-json/Cargo.toml
  crates/tombi-lexer/Cargo.toml
  crates/tombi-linter/Cargo.toml
  crates/tombi-parser/Cargo.toml
  crates/tombi-rg-tree/Cargo.toml
  crates/tombi-schema-store/Cargo.toml
  crates/tombi-server/Cargo.toml
  crates/tombi-syntax/Cargo.toml
  crates/tombi-toml-text/Cargo.toml
  crates/tombi-validator/Cargo.toml
  editors/zed/Cargo.toml
  extensions/tombi-cargo-extension/Cargo.toml
  extensions/tombi-uv-extension/Cargo.toml
  rust/serde_tombi/Cargo.toml
  rust/tombi-cli/Cargo.toml
  toml-test/Cargo.toml
  xtask/Cargo.toml
Labels: other-change

#307 Add crate goto definition
  Cargo.lock
  Cargo.toml
  crates/tombi-server/tests/goto_definition.rs
  extensions/tombi-cargo-extension/Cargo.toml
  extensions/tombi-cargo-extension/src/goto_declaration.rs
  extensions/tombi-cargo-extension/src/goto_definition.rs
  extensions/tombi-cargo-extension/src/lib.rs
Labels: enhancement

#313 feat: add goto definition on [tool.uv.workspace.members]
  crates/tombi-server/src/handler/goto_declaration.rs
  crates/tombi-server/tests/goto_declaration.rs
  crates/tombi-server/tests/goto_definition.rs
  extensions/tombi-cargo-extension/src/lib.rs
  extensions/tombi-uv-extension/src/goto_declaration.rs
  extensions/tombi-uv-extension/src/goto_definition.rs
  extensions/tombi-uv-extension/src/lib.rs
Labels: enhancement

#318 feat: enable goto features in configuration
  docs/src/routes/docs/configuration/index.mdx
Labels: documentation

#319 refactor: add Hash trait to Diagnostic struct
  crates/tombi-diagnostic/src/lib.rs
  crates/tombi-server/src/handler/diagnostic.rs
Labels: bug

#323 feat: add deprecated field to completion items
  crates/tombi-lsp/src/completion.rs
  crates/tombi-lsp/src/completion/completion_content.rs
  crates/tombi-lsp/src/completion/value/boolean.rs
  crates/tombi-lsp/src/completion/value/float.rs
  crates/tombi-lsp/src/completion/value/integer.rs
  crates/tombi-lsp/src/completion/value/local_date.rs
  crates/tombi-lsp/src/completion/value/local_date_time.rs
  crates/tombi-lsp/src/completion/value/local_time.rs
  crates/tombi-lsp/src/completion/value/offset_date_time.rs
  crates/tombi-lsp/src/completion/value/string.rs
  crates/tombi-lsp/src/completion/value/table.rs
  crates/tombi-schema-store/src/schema/table_schema.rs
Labels: enhancement

#324 Fix: folding range
  Cargo.toml
  crates/tombi-ast/src/impls/array_of_table.rs
  crates/tombi-ast/src/impls/key.rs
  crates/tombi-ast/src/impls/table.rs
  crates/tombi-date-time/src/private/date_time.rs
  crates/tombi-json-lexer/src/token.rs
  crates/tombi-lexer/src/token.rs
  crates/tombi-lsp/src/handler/folding_range.rs
  crates/tombi-rg-tree/src/red/node.rs
  crates/tombi-rg-tree/src/red/token.rs
  crates/tombi-text/src/range.rs
Labels: bug

#325 Fix: folding range comment
  crates/tombi-lsp/src/handler/folding_range.rs
  sample.toml
Labels: bug

#357 Fix schema loading
  crates/tombi-lsp/src/backend.rs
  crates/tombi-lsp/src/handler/initialized.rs
  crates/tombi-schema-store/src/store.rs
  rust/serde_tombi/src/ser.rs
Labels: bug

#409 docs: add CodeTabs component for command display
  docs/src/components/CodeTabs.tsx
  docs/src/routes/docs/installation.mdx
Labels: documentation

#410 docs: Update code
  docs/src/components/CodeTabs.tsx
  docs/src/routes/docs/installation.mdx
Labels: documentation

#445 feat: add uv workspace document links.
  crates/tombi-lsp/src/handler/document_link.rs
  extensions/tombi-extension-cargo/src/document_link.rs
  extensions/tombi-extension-uv/src/document_link.rs
  extensions/tombi-extension-uv/src/lib.rs
Labels: enhancement

#455 Fix document link2
  crates/tombi-extension/src/document_link.rs
  crates/tombi-lsp/tests/document_link.rs
  extensions/tombi-extension-cargo/src/document_link.rs
Labels: bug
